// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu9zOsxZKcjI0Xzadvb2lDJq-EKUcZViQ',
    appId: '1:1080215422648:web:96e556ce6fb9ade485d64d',
    messagingSenderId: '1080215422648',
    projectId: 'dynamic-links-sample-ca6a7',
    authDomain: 'dynamic-links-sample-ca6a7.firebaseapp.com',
    storageBucket: 'dynamic-links-sample-ca6a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjEx2Pujws5sK3FhWwPcAzB0__G9b8HsE',
    appId: '1:1080215422648:android:7ff6f9335144856c85d64d',
    messagingSenderId: '1080215422648',
    projectId: 'dynamic-links-sample-ca6a7',
    storageBucket: 'dynamic-links-sample-ca6a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwI_KLk3iDseul8MLzfW7AxWrWrLL6-R0',
    appId: '1:1080215422648:ios:5207e185db1e176885d64d',
    messagingSenderId: '1080215422648',
    projectId: 'dynamic-links-sample-ca6a7',
    storageBucket: 'dynamic-links-sample-ca6a7.appspot.com',
    androidClientId:
        '1080215422648-a0dp0d0i2ltnp646v2j0s2ir3bem3gkl.apps.googleusercontent.com',
    iosClientId:
        '1080215422648-v76n66u322jtlb35epm1ctnukvr4lsdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDynamicLinksSample3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwI_KLk3iDseul8MLzfW7AxWrWrLL6-R0',
    appId: '1:1080215422648:ios:5207e185db1e176885d64d',
    messagingSenderId: '1080215422648',
    projectId: 'dynamic-links-sample-ca6a7',
    storageBucket: 'dynamic-links-sample-ca6a7.appspot.com',
    androidClientId:
        '1080215422648-a0dp0d0i2ltnp646v2j0s2ir3bem3gkl.apps.googleusercontent.com',
    iosClientId:
        '1080215422648-v76n66u322jtlb35epm1ctnukvr4lsdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDynamicLinksSample3',
  );
}
